FROM nginx:1.18.0-alpine

ADD webfwk-static.tar /usr/share/nginx/html/webfwk/
ADD nginx.conf.d /etc/nginx/conf.d/default.conf
ADD webfwk-cert-all.pem /etc/nginx/cert/
ADD webfwk-cert-key.pem /etc/nginx/cert/
